### PR TITLE
Create portal-vehicle-guide.md

### PR DESCRIPTION
**Pull request by gmyenni**

### CODE REVIEW

**Comment by ethanwhite** [comment]
This looks great. What do you think about adding a couple of sentences as the beginning explaining why vehicle checks/maintenance are particularly important (you're going to be out in the middle of nowhere in the desert). A little 'why' can go a long way.

**Comment by gmyenni** [comment]
Added!

**Review by ethanwhite — APPROVED** [review]

**Review by patdumandan — COMMENTED** [review]
Would it be useful/relevant here if we add info. about the AZ Permit needing to be in the truck (not that anyone has ever asked me for it ever), and that this gets sent to Morgan at the beginning of each year (ideally)? Also, do we need to get a hideaway key box (given the new arrangement)? and add here a note to check it's still in its location upon arrival/before leaving Portal/Tucson?

**Comment by gmyenni** [comment]
I'm not sure why they stopped using the hide a key on the new truck, maybe because it doesn't fit in the hitch? I wouldn't trust it to stay just on the frame. If you can find somewhere enclosed, like in the hitch or inside a section of frame, where it won't rattle out, then yeah, I would definitely get a hide a key. And I'll add it.

**Review by patdumandan — APPROVED** [review]

**Pull request merged**
