### PR TITLE
Onboarding Clean up 

### PR DESCRIPTION
**Pull request by gmyenni**
- Declutter onboarding
- Add checklist and remove separate checklist page
- Move info to new Campus resources page
- Move Hao's git tip to Git Tips

### CODE REVIEW

**Comment by gmyenni** [comment]
Emergency Contact Info is a dead link. What's the best way to provide that?

**Review by ethanwhite — APPROVED** [review]
Looks great @gmyenni! The one thing I noticed is that there are still a few links to the old wiki on this page. Once those are updated to new links I think we're ready to go.

**Comment by gmyenni** [comment]
OMG they are insidious. I think I got them all now.

**Comment by ethanwhite** [comment]
Thanks!

**Pull request merged**
